---

- name: Check the system
  raw: uname -a
  register: OS

- name: Ubuntu pre-tasks
  include: ubuntu.yml
  when: '"Ubuntu" in OS.stdout'

- name: FreeBSD pre-tasks
  include: freebsd.yml
  when: '"FreeBSD" in OS.stdout'

- include: facts/main.yml
