---

- name: Ensure the local ssh directory is exist
  file:
    path: ~/.ssh/
    state: directory

- name: Copy the algo ssh key to the local ssh directory
  copy:
    src: "{{ SSH_keys.private }}"
    dest: ~/.ssh/algo.pem
    mode: '0600'
